DEFAULT_INVESTED_AMOUNT = 0
CHARITY_PROJECT_NAME_MAX_LENGTH = 100
FIELD_MIN_LENGTH = 1
SHEET_TITLE_TIME_FORMAT = '%Y/%m/%d %H:%M:%S'
SHEET_TITLE = 'Лист1'
SHEET_ID = 0
SHEET_ROW_COUNT = 100
SHEET_COLUMN_COUNT = 11
